### ISSUE TITLE
Something about "tf_pointSIFT_compile.sh"

### ISSUE THREAD

**Issue by xdck** [lixiang-ucas/D-FCN#2]
TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
TF_LIB=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')

#/bin/bash
/usr/local/cuda-8.0/bin/nvcc DFCN.cu -o DFCN_g.cu.o -c -O2 -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC

the "DFCN.cu" is not in "pointSIFT_op", so you can't only write "DFCN.cu" without its adress. 
Maybe there are something wrong?

**Comment by lixiang-ucas** [comment]
@xdck, sorry for the mistake. it should be pointSIFT.cu, not DFCN.cu. I've corrected all 'DFCN' to 'pointSIFT' in this file.
