### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by xdck** [lixiang-ucas/D-FCN#3]
您好，我按照您的要求下载了数据，但我看到您的程序中，有“.pickle”文件，想请问您是怎么对数据进行的预处理。期待您的回复。

**Comment by lixiang-ucas** [comment]
模型训练的时候数据没有做切片处理，每次直接从原始数据中切一个30m*30m的patch，然后采样固定数量的点（比如8192）。测试的时候用的pickle：你把数据按照30m*30m切片，然后把边缘特别小的和周边的合并。测试时因为每个切片点数不一样，所以batch size设置为1。预处理的话只是做了demean归一化，每个patch的坐标值减去该patch坐标的最小值。

**Comment by xdck** [comment]
> 模型训练的当时数据没有做切片处理，每次直接从原始数据中切一个30m _的补丁，然后采样固定数量的点（称为8192）。测试的时候用的腌料：你把数据按照30m_ 30m切片，然后将边缘边缘特别小的和周围的合并。测试时因为每个切片点数不一样，所以批处理大小设置为1。预先的话只是做了demean归一化，每个补丁的坐标值就是该补丁坐标的领导人。

非常感谢您的回复

**Comment by lydia9797** [comment]
作者你好～ 请问这里的“train_f = open('./Data/train_merge_min_norm_fea.pickle', 'rb')”这个训练集的pickle文件是怎么得到的 我看了您的其他评论  如果从原始数据中读取，那么train_xyz怎么定义呢？  num_batches = len(train_xyz)//BATCH_SIZE   这一部分怎么处理。以及代码中带有的训练数据  userdata的含义是什么？是#height above ground  那如何得到？论文里好像没有提及不是很明白  期待您的回复
